//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HakemOtomasyonTD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fikstur
    {
        public int fikstur_id { get; set; }
        public string fikstur_takim1 { get; set; }
        public string fikstur_takim2 { get; set; }
        public string fikstur_hafta { get; set; }
        public string fikstur_lig { get; set; }
        public string fikstur_saat { get; set; }
        public string fikstur_gun { get; set; }
        public string fikstur_salon { get; set; }
        public string fikstur_hakem { get; set; }
    }
}
