//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HakemOtomasyonTD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hakem
    {
        public int hakem_id { get; set; }
        public string hakem_adi { get; set; }
        public string hakem_soyadi { get; set; }
        public string hakem_tur { get; set; }
        public string hakem_klasman { get; set; }
        public string hakem_grup { get; set; }
        public string hakem_bolge { get; set; }
    }
}
