//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HakemOtomasyonTD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SporSalonu
    {
        public int salon_id { get; set; }
        public string salon_adi { get; set; }
        public string salon_sehir { get; set; }
        public string salon_ligi { get; set; }
        public string salon_diger { get; set; }
    }
}
