//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HakemOtomasyonTD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Takim
    {
        public int takim_id { get; set; }
        public string takim_adi { get; set; }
        public string takim_sehir { get; set; }
        public string takim_ligi { get; set; }
        public string takim_salon { get; set; }
        public string takim_diger { get; set; }
    }
}
